### ISSUE TITLE
unable to install my own tentacle

### ISSUE THREAD

**Issue by Amarchuk** [Drakkar-Software/OctoBot#1155]
## Step 1: Have you search for this issue before posting it?

Yep, try to find any info about it without success

## Step 2: Describe your environment
  * OS : Ubuntu 16.04
  * Python Version: 3.7.4 (`python -V`)
  * In case you are not using a binary version:
    * Branch: difficult to say
 
## Step 3: Describe the problem:
**Describe the bug**

I try to install my own tentacle (which is actually just an exact copy of existing `InstantMAEvaluator`) using instruction from https://github.com/Drakkar-Software/OctoBot/wiki/Customize-your-OctoBot#manual-installation (try both Manual and Automated),  but can't do that (even if that looks very simple).

**Expected behavior**

Tentacle to be installed and appear in Web UI.

### Steps to reproduce:

  1. Create a copy of `InstantMAEvaluator`, call it `MyOwnInstantMAEvaluator` and file containing it `simple_evaluator.py`
  2. add tentacle info in the top of this file, like
```python
"""
OctoBot Tentacle

$tentacle_description: {
    "name": "MyOwnInstantMAEvaluator",
    "type": "Evaluator",
    "subtype": "REAL_TIME",
    "version": "1.1.2",
    "requirements": [],
    "config_files": [],
    "config_schema_files": [],
    "tests":[]
}
"""
```
  3. Paste it into `OctoBot-Tentacles/tentacles/Evaluator/RealTime/Advanced/simple_evaluator.py` and add the line `from .simple_evaluator import *` to __init__.py
  4. Try to launch `Octobot` using ./launcher_app_linux, then click start octobot button and see that it can't starts because can't import this new evaluator
  5. I also try to use Automated installation - put a line with path to `simple_evaluator.py` into OctoBot-Tentacles/user/config.json and in `OctoBot` try to use `start.py` to install it (not sure how main `OctoBot` repository can know where `OctoBot-Tentacles` located).
  
### Observed Results:

  * What happened?

There are variety of errors, but in manual installation they all can be summarized by `Octobot` unable to import dependencies properly, like (relevant to InstantMAEvaluator code) `ModuleNotFoundError: No module named 'octobot_commons'`. If I just simply remove all dependencies of octobot_commons in my simple_evaluator.py and try again, I still can't do this is because `ModuleNotFoundError: No module named 'octobot_evaluators'`.

In automated for `python3.7 start.py -p install simple_evaluator` prompt says `OctoBot requires OctoBot-Tentacles-Manager, you can install it using python3 -m pip install -U OctoBot-Tentacles-Manager`, after `OctoBot-Tentacles-Manager` installation - 

```bash
Traceback (most recent call last):
  File "start.py", line 21, in <module>
    from octobot.commands import exchange_keys_encrypter, start_strategy_optimizer, start_bot, data_collector, \
  File "/mnt/sdb2/octobot/OctoBot/octobot/commands.py", line 35, in <module>
    from octobot.logger import init_logger
  File "/mnt/sdb2/octobot/OctoBot/octobot/logger.py", line 23, in <module>
    from octobot_channels.channels.channel import get_chan
ModuleNotFoundError: No module named 'octobot_channels'
```

Maybe I miss something important and just done it all in a wrong way.
Thanks

P.S. I also want to mention that wiki page I refer to contains `Examples with the tentacles created in the **Module creation** section:`. Does this section exist?

**Comment by GuillaumeDSM** [comment]
Hello @Amarchuk,

Thanks for your interest in OctoBot and the details you provided !
Errors related to ```octobot_commons```, ```octobot_channels``` and ```octobot_evaluators``` mean you are using some parts of OctoBot 0.4 (that is using this repos) and some part of 0.3 (which only uses OctoBot and OctoBot-Tentacles-Manager in version < 2.0.0).

If you are using OctoBot from the default git branch: ```dev``` then you want to run OctoBot 0.3.8 which is the current official version (0.4 is in late dev stage but not ready for tests yet).

I think your issue is that you have OctoBot-Tentacles-Manager in version compatible with OctBot 0.4, not 0.3. To solve this you can use the following command: ```python3 -m pip install -U "OctoBot-Tentacles-Manager<2.0.0"``` that should solve your import issues and you should be able to use your tentacle.

For OctoBot to see and use your tentacle, here is the process (not automated):
- add an import line to import your tentacle in the ```__init__.py``` associated file
- add the class of your evaluator into your ```tentacles/Evaluator/evaluator_config.json``` file alongside the others (otherwise OctoBot will import it but won't use it. This part was missing on the wiki, I'm adding it.

Note: this process is a bit complicated and is getting much simpler with 0.4. When the beta will be out, we will update the wiki accordingly

**Comment by Amarchuk** [comment]
@GuillaumeDSM thanks for the useful and fast reply! Yep, I understand that things can be a bit tricky in the middle of development process (and to be honest, fell lost a little in all these subrepos and branches). I will try your suggestions on nearest Mon or so and will reply here

**Comment by Amarchuk** [comment]
I check this method and seems like everything works as expected (thanks again) except one minor (?) issue:

I can see `MyOwnInstantMAEvaluator` in 127.0.1.1:5001/tentacles, but in log the line `ERROR    TentacleManager      No tentacle found for 'MyOwnInstantMAEvaluator'` appears and I also can't find this evaluator in **Compatible evaluation strategies** (but maybe I shouldn't, don't read code carefully).

P.S. in wiki `Only 2 steps are necessary...` should be `Only 3 steps are necessary...`

**Comment by Amarchuk** [comment]
And a following question, which is related to the topic: I try to create my own trading mode for testing purposes and do the same as with evaluator - add it to `OctoBot/tentacles/Trading/Mode/Advanced`, write in the `__init__.py`, add schema and parameters json into `OctoBot/tentacles/Trading/Mode/config` and add mode name into `trading_config.json` (and switch every other to false). But on startup I get 

```python
2020-05-14 17:12:59,478 ERROR    get_activated_trading_mode Error when loading a trading mode: Cant find PGPDailyTradingMode module referenced in tentacles/Trading/trading_config.json file
 2020-05-14 17:12:59,479 ERROR    OctoBot Launcher     OctoBot Exception : Please ensure your tentacles/Trading/trading_config.json file is valid and at least one trading mode is activated
Traceback (most recent call last):
  File "tools/commands.py", line 110, in start_bot
    await bot.initialize()
  File "core/octobot.py", line 68, in initialize
    await self.exchange_factory.create()
  File "core/exchange_factory.py", line 58, in create
    await self._create_exchange_traders(exchange_class_string)
  File "core/exchange_factory.py", line 91, in _create_exchange_traders
    self._create_trading_mode(exchange_inst)
  File "core/exchange_factory.py", line 129, in _create_trading_mode
    self.trading_mode = get_activated_trading_mode(self.octobot.get_config())(self.octobot.get_config(),
  File "trading/util/trading_config_util.py", line 48, in get_activated_trading_mode
    raise ConfigTradingError(f"Please ensure your {CONFIG_TRADING_FILE_PATH} file is valid and at least one trading "
tools.errors.ConfigTradingError: Please ensure your tentacles/Trading/trading_config.json file is valid and at least one trading mode is activated
 2020-05-14 17:12:59,484 ERROR    OctoBot Launcher     OctoBot can't start without a valid tentacles/Trading/trading_config.json configuration file.
This file is generated on tentacle installation using the following command:
start.py -p install all
```

So it seems like unlike for evaluator this way to add new trading modes need additional actions (with tentacle-manager?). I try to figure out this by myself reading part where exception rises (which is very straightforward), but still confused about it.

**Comment by GuillaumeDSM** [comment]
Hi !
About **Compatible evaluation strategies** these are defined in the file of your strategy, just add the class of the evaluators you want there.
The schema file in tentacles config is only used to generate the config page for your tentacle, if you don't need it, there is no need to make a schema file.
For this error, it looks like python doesn't manage to import the trading mode (the process is to import all trading modes and use the one that is activated in config. If yours has not been imported you will get this error.

It's probably a missing python ```__init__.py``` file somewhere.
Trading modes and evaluators work the same way, no need for special actions for them: extend the parent class, add them in  ```__init__.py``` so that python can see them and add them into trading_config.json.

**Comment by Amarchuk** [comment]
Thanks! Looks like I can successfully import now evaluator, mode and strategy and can start actual developing.

**Comment by Amarchuk** [comment]
BTW I think that this can be closed now.
