### ISSUE TITLE
Backtesting only with ONE_DAY Timeframe?

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [Drakkar-Software/OctoBot#1287]
## Step 1: Have you search for this issue before posting it?

Yes, found nothing.

## Step 2: Describe your environment
  * OS : Raspberry Pi 4
  * Python Version: 3.7.3
  * In case you are not using a binary version:
    * Branch: 0.4.0
 
## Step 3: Describe the problem:
**Describe the bug**
Wanted to test the InstantFluctuationsEvaluator to get more active trades. Unfortunately several timeframes were not accepted although they should be included in the historical data.

**Expected behavior**
I expected that all specified timeframes of the historical data would work.

### Relevant code exceptions or logs:
 
![2020-08-15 19_11_01-OctoBot und 4 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/23531655/90317751-c7fc2600-df2b-11ea-8a76-7fbcb35b9197.png)

![2020-08-15 19_11_25-OctoBot und 4 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/23531655/90317757-ce8a9d80-df2b-11ea-8f59-fd5b10e4913b.png)

![2020-08-15 19_11_13-OctoBot und 4 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/23531655/90317760-d34f5180-df2b-11ea-801e-127fbb8b6628.png)

**Comment by Herklos** [comment]
Thanks for reporting @ChristianFeldmannHamm, I'll try to reproduce it

**Comment by Herklos** [comment]
Hi @ChristianFeldmannHamm, you can't use other time frame for `InstantFluctuationsEvaluator`. It has a fixed timeframe value that cannot be changed. That's why you can't set its timeframe to 1d.

**Comment by GuillaumeDSM** [comment]
To be more specific, `InstantFluctuationsEvaluator` can only handle one time frame at a time.
The warnings you are getting here are a bit more complicated and we need to figure out a way to make them clearer.

Basically backtesting is using the maximum available data. The issue here is that exchange are (usually) not giving all of their data: they give the last X candles (500 for binance). Therefore in your data files you have 500 1h candles, 500 1m candles etc. These candles are always the most recent ones.
That means that when running a backtesting on 1h + 1d time frames, the maximum backtesting range is not 1h + 1d with 500 candles each but the time range where **both** 1h and 1d have data: there the past 500 hours (500 1h candles and approximately 20 1d candles). 
As a result, if you include 1m candles, very little other time frames can be included because of this common time range situation.

Now regarding your situation with `InstantFluctuationsEvaluator`. `InstantFluctuationsEvaluator` is a real-time evaluator, meaning it is supposed to wake up strategies when it sees something but it's not supposed to impose its time frame, it uses the **shortest available without changing the strategy setup**. Because of that, real time evaluator time frames are not forced into backtesting, they use the shortest activated time frame (1h in your situation). If you really want to use shortest time frame, you can activate them in your strategy config but it will reduce the total backtestable time because of this 500 candles limit on binance.

Hopefully it's now clearer

**Comment by GuillaumeDSM** [comment]
I added [this FAQ content](https://github.com/Drakkar-Software/OctoBot/wiki/Frequently-asked-questions-(FAQ)#why-backtesting-is-not-using-all-available-data-) to address this issue, hopefully that will help
