### ISSUE TITLE
Docker image update for Raspberry / arm

### ISSUE THREAD

**Issue by damajor** [Drakkar-Software/OctoBot#1579]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/Drakkar-Software/OctoBot/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * OS : [RaspberryOS] 
 
## Step 3: Describe the problem:

The docker image on Docker Hub is only for x86 architecture.

**Expected behavior**

To be consistent with the documentation (which gives some tips to use OctoBot on Raspberry PI), the users should be able to pull an arm version of the docker image of OctoBot (which is not the case at this moment).

**Comment by Herklos** [comment]
Hi @damajor, we currently have an issue with one of the library we use in OctoBot that prevent arm64 docker image to build. We are waiting for a new release of this library that will fix the issue.

**Comment by Herklos** [comment]
We will keep this issue up to date with the latest information about the arm64 image.

**Comment by Herklos** [comment]
In the next release, binary and installation from pypi (pip) will be available for raspberry users (arm64).

**Comment by damajor** [comment]
Which library is causing issue ?

**Comment by Herklos** [comment]
> Which library is causing issue ?

aiohttp (https://github.com/aio-libs/aiohttp/issues/5366)

**Comment by gabriel-milan** [comment]
Hi there.

Before anything else, thanks for this amazing project!

I've been trying to run OctoBot on my RPi, that's how I got here.
Reading that same issue on aiohttp you've mentioned, and I see that you've tried bumping aiohttp to 3.7.4 on https://github.com/Drakkar-Software/OctoBot/commit/27180f6ff7eadb0a834dc7c7cc1c8338f72988f0 but, unfortunately, as noticed on https://github.com/aio-libs/aiohttp/issues/5366#issuecomment-786705292, this version still has the same issue with chardet dependency. A couple of days later, they have released [3.7.4.post0](https://pypi.org/project/aiohttp/3.7.4.post0/) (https://github.com/aio-libs/aiohttp/issues/5366#issuecomment-792062354) which, according to commit https://github.com/aio-libs/aiohttp/commit/934e5cbcc3ba8a952ff854c12b290ecdbb0856cb, fixes the chardet issue.

Hope this helps with the arm/v7 docker builds. I have tried to build it on my own, but unfortunately I'm facing an issue with cryptography, due to its recent dependency on Rust (https://github.com/pyca/cryptography/issues/5771). I could just work around this but didn't intend to mess with your Dockerfile. Do you think it's possible for the arm/v7 builds to be back?

**Comment by gabriel-milan** [comment]
@damajor the latest build of the Docker image now supports `arm/v7` again. Please check https://hub.docker.com/r/drakkarsoftware/octobot/tags?page=1&ordering=last_updated

I think that's probably OK for us to close this now.

**Comment by Herklos** [comment]
> @damajor the latest build of the Docker image now supports `arm/v7` again. Please check https://hub.docker.com/r/drakkarsoftware/octobot/tags?page=1&ordering=last_updated
> 
> I think that's probably OK for us to close this now.

Yes it's working, thanks @gabriel-milan !

**Comment by Nrddy** [comment]
I use Tipi on my Raspbery Pi but i am not a big coder.. how hard would it be to create Ocotbot as a Tipi app? Then it would be a Very easy install and self hosted alternative. Tipi is just a Docker and apps are just run on it.
https://github.com/meienberger/runtipi/wiki/Adding-your-own-app
