### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Lucky-92** [Drakkar-Software/OctoBot#274]
.......
**Set default configuration...**
La syntaxe de la commande n'est pas correcte.
**Installing modules...**
 2018-06-29 07:15:29,487 INFO     OctoBot Launcher     Version : 0.1.3_2-beta
 2018-06-29 07:15:29,488 INFO     OctoBot Launcher     Loading config files...
 2018-06-29 07:15:29,489 ERROR    root                   File "start.py", line 64, in <module>
    config = load_config()
  File "C:\Users\luc\bot_002\OctoBot\config\config.py", line 24, in load_config
    raise Exception(error_str)
NoneType: None
 2018-06-29 07:15:29,489 ERROR    root                 <class 'Exception'>: Error when load config : file opening failed
 ([Errno 2] No such file or directory: 'config.json')
NoneType: None

C:\Users\luc\bot_002\OctoBot>

**Comment by Herklos** [comment]
Hi, did you use "OctoBot/docs/install/windows/**windows_installer.bat**" ?

You don't have the required *config.json* file.
You can manually create it by copying the **config/default_config.json** into your root folder as "config.json".

Or you can run **windows_installer.bat**

**Comment by Lucky-92** [comment]
Dear Herklos,

Thank you for your quick answer.
Actually, I used the windows_installer.bat, but it seems that any copy of config.json had been achieved.
I will try to perform the manual copy as you recommand.

Best regards,
Lucky92.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Herklos** [comment]
Fixed by https://github.com/Drakkar-Software/OctoBot/commit/af0f58b9916ad601791b4710081e7315b9d60b5b

Reopen if needed :smiley:

**Comment by techsoulman** [comment]
Hi There, I am having a very similar problem installing.

I have uploaded a screenshot because the prompt closes moments after giving the message.

Also worth noting that no folders appear to have been created for OctoBot so I have no idea where to put config.json file, I tried creating the  Appdata/Temp/etc/etc path and adding it there and also creating an OctoBot folder in program files and adding it there but neither helped.

![Screenshot (18)](https://user-images.githubusercontent.com/16014225/140901775-af1aeb7e-7af2-49c3-b05e-c983573db3dd.png)
