### ISSUE TITLE
[Developer Env] install (pytest) 

### ISSUE THREAD

**Issue by pudong1** [Drakkar-Software/OctoBot#285]
## Step 2: Describe your environment
  * OS : [Windows, .] 
  * Python Version: 3.6
  * Branch: Master | Dev
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

 
## Step 3: Describe the problem:
**Describe the bug**

**Expected behavior**
When I run the commond: pytest tentacles/tests

It produced the following errors:  pytest: error: unrecognized arguments: --pep8

Doest it means that I need to install the module pep8 or something others I need to fix?

Best regards,

Bot1bot1

### Steps to reproduce:

  1. Simply run the command : 'pytest tentacles/tests' or ' pytest tests '
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
 pytest: error: unrecognized arguments: --pep8

### Relevant code exceptions or logs:
 
```
// paste your log here
```
![default](https://user-images.githubusercontent.com/40735848/42215145-29add680-7ef0-11e8-99ba-ef56b9342b58.png)

**Comment by Herklos** [comment]
Hi pudong1 !

The process of creating a developer environment will be soon described in [Developer](https://github.com/Drakkar-Software/OctoBot/wiki/Developer).

For now you only have to execute this command : 
`pip3 install -r dev_requirements.txt` 
or
`python -m pip install -r dev_requirements.txt` (if you didn't put pip in your Windows PATH)
<br><br>
Thanks again for using Octobot in beta version !
Herklos

**Comment by pudong1** [comment]
Hi Herklos,

Thanks for the reply. With the installation of the developer 
environment, I am able to run:  "pytest test", and passed 100% with the 
defaulted settings.  I am trying to a construct a bot on Bitmex, it 
seems that changing the exchange name from Binance to bitmex does not 
work. I also saw there is a file called "test_binance_websocket.py" that 
is dedicated for Binance, which  needs to be replaced, am I right?

Apart from that, what else I need to do for construction for bitmex? I 
am not very familiar with those things, it would be nice if you could 
provide some details.

Thanks in advance!

pudoing1



------ 原始信息 ------
来自: "Herklos" <notifications@github.com>
收件人: "Drakkar-Software/OctoBot" <OctoBot@noreply.github.com>
抄送人: "pudong1" <pupu35088@gmail.com>; "Author" 
<author@noreply.github.com>
发送: 2018/7/3 20:16:21
主题: Re: [Drakkar-Software/OctoBot] pytest (#285)

**Comment by Herklos** [comment]
Hi pudong1,

If you won't use binance (but only bitmex) the only thing you can do for this test is removing it.
Moreover if bitmex supports Websocket requests you can also create à new file named "test_bitmex_websocket.py" and "bitmex_websocket.py" in trading/exchanges/websocket/implementations to develop this feature.
For now, you can just remove this file that your Octobot doesn't need because you will only use bitmex.

**Comment by GuillaumeDSM** [comment]
Hi pudong1,
You actually don't even have to replace **test_binance_websocket.py**, you can leave it as is. All tests should pass if you leave all data in **tests/static/config.json**. To test bitmex, you can add a bitmex config in this same file. **tests/static/config.json** should then have something like this:
```json
"exchanges": {
    "binance": {
      "api-key": "",
      "api-secret": ""
    },
    "bitmex": {
      "api-key": "",
      "api-secret": ""
    }
}
```
Using this solution, all existing tests should pass and you can add tests for bitmex additionnaly to the existing ones.

About the second part of the question, we don't automatically test ccxt exchange specific interfaces (we leave it to ccxt), therefore if you want to use the rest interface to interact with bitmex, no tests are necessary to be built. 
The only existing exchanges specific tests are in **test_binance_websocket.py** and it tests the implementation of the websocket interface of binance exchange, which is the only websocket interface we developped for now.
For you, if you want to use the websocket service of OctoBot to interact with bitmex (if bitmex provides a websocket interface), you will have to implement an equivalent of **trading/exchanges/websocket/implementations/binance_websocket.py** for bitmex. In order to do this, you need to extend the **AbstractWebSocket** class and implement all abstract methods (just like **binance_websocket.py** does). 
In this case it makes sense to create a **test_bitmex_websocket.py** in OctoBot's tests to test your websocket interface implementation.

Thank you for using OctoBot !

Guillaume
